"""Initial migration

Revision ID: 77e13e6b6619
Revises: 
Create Date: 2023-08-13 20:39:25.065849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77e13e6b6619'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reptiles',
    sa.Column('reptile_id', sa.Integer(), nullable=False),
    sa.Column('reptile_name', sa.String(length=80), nullable=False),
    sa.Column('reptile_fact', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('reptile_id'),
    sa.UniqueConstraint('reptile_fact'),
    sa.UniqueConstraint('reptile_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reptiles')
    # ### end Alembic commands ###
